### ISSUE TITLE
Why doesn't this exist yet?

### ISSUE THREAD

**Issue by googleygoggles** [Lightn1ng/tacOS#1]
Seriously man! WHY IS IT NOT DONE

**Comment by Lightn1ng** [comment]
I made the repository about 2 minutes ago dude

**Comment by googleygoggles** [comment]
It should have been DONE 2 minutes ago. You're getting lazy

**Comment by googleygoggles** [comment]
# DONE I SAY

**Comment by Lightn1ng** [comment]
# NOT DONE I SAY

**Comment by googleygoggles** [comment]
I'm firing you from tacOS Co.
