### ISSUE TITLE
Issue: I don't know Java

### ISSUE THREAD

**Issue by Lightn1ng** [Lightn1ng/tacOS#2]

**Comment by googleygoggles** [comment]
Wanna learn together?

**Comment by Lightn1ng** [comment]
Sure *brings out giant Java book*

**Comment by googleygoggles** [comment]
I CAN SHOW YOU THE CODE. SHINING SHIIMMERING SPLENDIID

**Comment by Lightn1ng** [comment]
I love how we're using github issues to communicate instead of something SUPPOSED to chat

**Comment by googleygoggles** [comment]
Tell me princess when did you last let your runtime, decide?
A WHOLE NEW COOOODE
A NEW FANTASTIC IDE

**Comment by googleygoggles** [comment]
lol yeah
